RDCT-1171: use bootstrapping wrapper instead of relying on JAVA_HOME being set
GitOrigin-RevId: dd53833e77c23707182ee4b4ef812f49f59a8408

diff --git a/native/XPlatLauncher/resources/TestProject/gradlew b/native/XPlatLauncher/resources/TestProject/gradlew
--- a/native/XPlatLauncher/resources/TestProject/gradlew
+++ b/native/XPlatLauncher/resources/TestProject/gradlew
@@ -115,6 +115,97 @@ esac
 CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar
 
 
+# GRADLE JVM WRAPPER START MARKER
+BUILD_DIR="${HOME}/.local/share/gradle-jvm"
+JVM_ARCH=$(uname -m)
+JVM_TEMP_FILE=$BUILD_DIR/gradle-jvm-temp.tar.gz
+if [ "$darwin" = "true" ]; then
+    case $JVM_ARCH in
+    x86_64)
+        JVM_URL=https://download.oracle.com/java/17/archive/jdk-17.0.3.1_macos-x64_bin.tar.gz
+        JVM_TARGET_DIR=$BUILD_DIR/jdk-17.0.3.1_macos-x64_bin-1bcf03
+        ;;
+    arm64)
+        JVM_URL=https://download.oracle.com/java/17/archive/jdk-17.0.3.1_macos-aarch64_bin.tar.gz
+        JVM_TARGET_DIR=$BUILD_DIR/jdk-17.0.3.1_macos-aarch64_bin-297fa2
+        ;;
+    *) 
+        die "Unknown architecture $JVM_ARCH"
+        ;;
+    esac
+elif [ "$cygwin" = "true" ] || [ "$msys" = "true" ]; then
+    JVM_URL=https://download.oracle.com/java/17/archive/jdk-17.0.3.1_windows-x64_bin.zip
+    JVM_TARGET_DIR=$BUILD_DIR/jdk-17.0.3.1_windows-x64_bin-d6ede5
+else
+    JVM_ARCH=$(linux$(getconf LONG_BIT) uname -m)
+     case $JVM_ARCH in
+        x86_64)
+            JVM_URL=https://download.oracle.com/java/17/archive/jdk-17.0.3.1_linux-x64_bin.tar.gz
+            JVM_TARGET_DIR=$BUILD_DIR/jdk-17.0.3.1_linux-x64_bin-9324ae
+            ;;
+        aarch64)
+            JVM_URL=https://download.oracle.com/java/17/archive/jdk-17.0.3.1_linux-aarch64_bin.tar.gz
+            JVM_TARGET_DIR=$BUILD_DIR/jdk-17.0.3.1_linux-aarch64_bin-319da6
+            ;;
+        *) 
+            die "Unknown architecture $JVM_ARCH"
+            ;;
+        esac
+fi
+
+set -e
+
+if [ -e "$JVM_TARGET_DIR/.flag" ] && [ -n "$(ls "$JVM_TARGET_DIR")" ] && [ "x$(cat "$JVM_TARGET_DIR/.flag")" = "x${JVM_URL}" ]; then
+    # Everything is up-to-date in $JVM_TARGET_DIR, do nothing
+    true
+else
+  echo "Downloading $JVM_URL to $JVM_TEMP_FILE"
+
+  rm -f "$JVM_TEMP_FILE"
+  mkdir -p "$BUILD_DIR"
+  if command -v curl >/dev/null 2>&1; then
+      if [ -t 1 ]; then CURL_PROGRESS="--progress-bar"; else CURL_PROGRESS="--silent --show-error"; fi
+      # shellcheck disable=SC2086
+      curl $CURL_PROGRESS -L --output "${JVM_TEMP_FILE}" "$JVM_URL" 2>&1
+  elif command -v wget >/dev/null 2>&1; then
+      if [ -t 1 ]; then WGET_PROGRESS=""; else WGET_PROGRESS="-nv"; fi
+      wget $WGET_PROGRESS -O "${JVM_TEMP_FILE}" "$JVM_URL" 2>&1
+  else
+      die "ERROR: Please install wget or curl"
+  fi
+
+  echo "Extracting $JVM_TEMP_FILE to $JVM_TARGET_DIR"
+  rm -rf "$JVM_TARGET_DIR"
+  mkdir -p "$JVM_TARGET_DIR"
+
+  case "$JVM_URL" in
+    *".zip") unzip "$JVM_TEMP_FILE" -d "$JVM_TARGET_DIR" ;;
+    *) tar -x -f "$JVM_TEMP_FILE" -C "$JVM_TARGET_DIR" ;;
+  esac
+  
+  rm -f "$JVM_TEMP_FILE"
+
+  echo "$JVM_URL" >"$JVM_TARGET_DIR/.flag"
+fi
+
+JAVA_HOME=
+for d in "$JVM_TARGET_DIR" "$JVM_TARGET_DIR"/* "$JVM_TARGET_DIR"/Contents/Home "$JVM_TARGET_DIR"/*/Contents/Home; do
+  if [ -e "$d/bin/java" ]; then
+    JAVA_HOME="$d"
+  fi
+done
+
+if [ '!' -e "$JAVA_HOME/bin/java" ]; then
+  die "Unable to find bin/java under $JVM_TARGET_DIR"
+fi
+
+# Make it available for child processes
+export JAVA_HOME
+
+set +e
+
+# GRADLE JVM WRAPPER END MARKER
+
 # Determine the Java command to use to start the JVM.
 if [ -n "$JAVA_HOME" ] ; then
     if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
