[JEWEL-906] Mandate valid JEWEL issue ID in single commit messages
This adds a check to GitHub Actions that validates:
 1. The PR has only one commit
 2. The commit message starts with "[JEWEL-xxx] ", where xxx is a
    positive number

These checks only run if the PR contains changes in the Jewel folder
other than `AllIconsKeys`. That gets autogenerated by a script when
any changes are made to IJP icons, and is high-traffic. Any IJP dev
can run the script, and it should not block PRs added elsewhere in the
IJP that update the icons.

Additionally, if there is a `JEWEL_YT_TOKEN` secret defined, the check
also validates that the referenced issue is valid — meaning, it
exists, is not resolved, and not a draft.

closes https://github.com/JetBrains/intellij-community/pull/3138

(cherry picked from commit a9c2b18e9605f96b23647c1466156832be8dde00)


(cherry picked from commit e59487e8dd19b51097c21a770a0a3da81d3f6c14)

IJ-MR-173299

GitOrigin-RevId: aa4846193c951eb66d84c2aedb68ac83ce87c726

diff --git a/.github/workflows/jewel_checks.yml b/.github/workflows/jewel_checks.yml
--- a/.github/workflows/jewel_checks.yml
+++ b/.github/workflows/jewel_checks.yml
@@ -11,12 +11,14 @@ defaults:
 
 jobs:
   checks:
+    name: CI code checks
     runs-on: ubuntu-latest
 
     steps:
       - uses: actions/checkout@v4
+        name: Check out repository
 
-      - name: Set up JDK 21
+      - name: Set up JBR 21
         uses: actions/setup-java@v4
         with:
           java-version: 21
@@ -37,3 +39,54 @@ jobs:
       - name: Run ktfmt and ktlint checks on IDE plugin
         # We can only use static analysis that doesn't depend on compilation in the IDE plugin
         run: ./gradlew :samples:ide-plugin:ktfmtCheck :samples:ide-plugin:lintKotlinMain --continue --no-daemon
+
+  check_paths:
+    name: Check changed files
+    runs-on: ubuntu-latest
+    permissions:
+      pull-requests: read
+    outputs:
+      run_formalities: ${{ steps.filter.outputs.run_formalities }}
+
+    steps:
+      - uses: actions/checkout@v4
+        name: Check out repository
+
+      - uses: dorny/paths-filter@v3
+        name: Check which files are changed
+        id: filter
+        with:
+          filters: |
+            run_formalities:
+              - '!all(platform/jewel/ui/generated/org/jetbrains/jewel/ui/icons/AllIconsKeys.java)'
+
+  formalities:
+    name: PR formalities
+    runs-on: ubuntu-latest
+    needs: check_paths
+    if: needs.check_paths.outputs.run_formalities == 'true'
+
+    steps:
+      - uses: actions/checkout@v4
+        name: Check out repository
+        with:
+          # Assume we don't have more than 10 commits in the branch —
+          # if we do, it'll fail on the single-commit check anyway.
+          fetch-depth: 10
+
+      - name: Validate PR has single commit
+        run: |
+          commit_count=$(git rev-list --count ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }})
+          if [ "$commit_count" -ne 1 ]; then
+            echo "ERROR: This pull request must contain exactly one commit."
+            echo "Please squash your commits into a single commit."
+            exit 1
+          fi
+
+      - name: Grant execute permission for validation script
+        run: chmod +x validate-commit-message.sh
+
+      - name: Validate commit message
+        env:
+          JEWEL_YT_TOKEN: ${{ secrets.JEWEL_YT_TOKEN }}
+        run: ./validate-commit-message.sh "${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}"
